Week3 프로젝트 세팅
kakao-tech-campus-2nd-step3/Team11_BE pull request #2
Opened 2024-09-20 13:36 UTC by JaeanHan

질문 사항들은 readme에 기재했습니다! 확인 부탁 드립니다!!

2024-09-21 14:35 UTC, yoo-jaein requested changes
3주차 고생 많으셨습니다!
리드미 구체적으로 적어주셔서 잘 읽었습니다.

템플릿이라는 개념이 잘 이해되지 않는데,
혹시 서비스의 구체적인 기획서가 있다면 공유해주세요.
프로젝트 리뷰에 참고하겠습니다 :)

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/global/exception/BusinessException.java
> +public class BusinessException extends RuntimeException {
👍

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/global/MyCrudRepository.java
> +public interface MyCrudRepository<T, ID> extends Repository<T, ID> {
MyCrudRepository가 꼭 필요한 클래스일까요?
Spring Data Jpa를 사용하고 있다면 JpaRepository 또는 CrudRepository를 상속받는 경우 findAll, save, findById 등 많은 기본 CRUD 작업에 대한 메서드들이 자동으로 생성됩니다.

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/global/handler/GlobalExceptionHandler.java
> +        System.out.println(e);
System.out.println() 대신 SLF4J Logger를 사용해서 로깅하는 것이 좋습니다.
```java
private static final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class);
...
logger.error("...");
```
- https://lusida-coding.tistory.com/142 참고

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/global/response/ResultCode.java
> +    GET_ALL_PRODUCTS_SUCCESS(HttpStatus.OK, "P001", "모든 제품 조회 성공"),
로직 성공마다 Code를 따로 두면 너무 많아질 것 같아요
성공 Code는 하나로 통일해도 될 것 같습니다.

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/global/utils/ResponseHelper.java
> +public class ResponseHelper {
👍

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/global/utils/ResponseHelper.java
> +public class ResponseHelper {
ResponseHelper와 같은 유틸 클래스는 상속과 인스턴스화를 금지시키는 것이 좋습니다.
- https://camel-context.tistory.com/37 참고

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/global/utils/ResponseHelper.java
> +    public static ResponseEntity<SimpleResultResponseDto> createSimpleResponse(ResultCode resultCode, Map<String, String> headers) {
일급 컬렉션을 사용하는 방향도 고려해보세요
- https://jojoldu.tistory.com/412 참고

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/template/controller/TemplateController.java
> +    @PostMapping("")
("")은 생략이 가능합니다

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/template/controller/TemplateController.java
> +    public ResponseEntity<TemplateDomain> getTemplateById(@PathVariable(name = "id") Long id) {
어떤 id인지 명시해주는 것이 좋습니다. (예: /{template-id})

2024-09-21 14:35 UTC, yoo-jaein commented on boomerang/src/main/java/boomerang/template/controller/TemplateController.java
> +        System.out.println(e);
여기도 별도의 로깅 프레임워크를 사용하는 것이 좋을 것 같아요

2024-09-21 14:46 UTC, yoo-jaein commented
> 컨트롤러용 DTO와 서비스용 DTO를 각각 두어서 서비스 단에서는 추가적인 객체 변환 로직을 두지않게 하는 것이 적절할지 고민입니다! 

- 작은 프로젝트나 간단한 CRUD 작업이 주를 이루는 경우에는 하나의 DTO를 사용하는 것이 효율적입니다. (두 개의 DTO 필드 구성이 크게 다르지 않은데 굳이 분리하는 경우 매핑 과정이 추가되며 프로젝트 복잡도만 더 올라갈 수 있습니다.) 현재 프로젝트에서는 DTO를 하나만 두어도 괜찮을 것 같습니다. 하나로 진행하되 앞으로 로직이 복잡해진다면 추가로 DTO를 만들면 좋을 것 같아요.

> API 요청이 정상응답으로 끝났을때도 성공 code를 작성해야할지

- 에러 코드와 에러 메시지만 잘 정의해놓는다면 성공 코드를 세세히 관리할 필요는 없을 것 같아요. https://github.com/kakao-tech-campus-2nd-step3/Team11_BE/pull/2/files#r1769583383 여기에도 코멘트를 남겼는데, P002, 단일 제품 조회 성공.. 이런 정보는 클라이언트에서 정말 필요한 내용일지 생각해보시면 좋겠어요. 대부분 클라의 경우 HttpStatus 200 OK & api 응답 json 으로 서버 작업의 성공 여부와 결과를 충분히 이해할 수 있답니다.

2024-09-22 08:49 UTC, jinseohyun1228 commented
답변 감사합니다! 멘토님 🙇🙇 

### "템플릿"에 대해서
>템플릿이라는 개념이 잘 이해되지 않는데,

- 코드 통일성을 위해서 `boomerang/src/main/java/boomerang/template` 폴더에 구격화된 코드를 들을` 탬플릿코드`로 이름 붙였습니다.
해당 폴더에는 미리 스타일을 구체화한 예시 코드가 포함되고, 실제 개발에 활용하기로 하였습니다. 

### 질문1에 대한 추가 고민
- Entity 나 Request의 데이터가 바뀌어도, Test 코드에 영향을 주지 않음 => 실질적인 로직을 담당하는 Controller, Service, Repository가 수정이 되지 않기 때문

### 질문2에 대한 추가 고민 . API 응답 형식에 대해서 
- 아래 3가지 중 어떤 응답 형식이 좋을지, 또는 다른 좋은 방법이 있을 지 궁금합니다. 멘토님은 어떻게 생각하시나요?

#### case 1. status 와 데이터만으로 응답
```
status : 201
{
    data : 1
}
```
- 장점 : 간단하다.
- 단점 : 프론트에서 현재 어떤 api 요청을 하였는지 알기 어렵거나, 같은 api 라 해도, 사용자에 따른 다른 메시지가 필요할 때, 알아보기가 힘들 수 있다 ex) 관리자 ~~~ 의 데이터, 사용자 ~~~ 의 데이터

#### case 2. status를 200으로 고정하고, 메세지와 데이터로 응답
```
status : 200
{
    message : 정상 반환
    data : 1
}
``` 
- 장점 : Controller 코드 작성하기가 간단해지고, 메세지를 통해 여러 상황에 대처할 수 있다 
- 단점 : Error 가 발생했을 때의 응답 형태와 조금 달라진다

#### case 3. stauts 와 에러코드, 메세지, 데이터로 응답
```
status : 201
{
    code : M001
    message : 정상 반환 
    data : 1
}
```

- 장점 : 응답 내부에 코드 정보를 제공해 일관성 있게 ResultCode 에서 Enum 형태로 반환 코드를 관리할 수 있다. 에러 반환과 동일한 응답 형태로 관리할 수 있다 
- 단점 : Controller 가 복잡해지고, 매번 Enum 처리를 위해 처리해야할 과정이 길다

2024-09-22 08:51 UTC, jinseohyun1228 commented
답변감사합니다 ㅎㅎ 리뷰 받은 내용으로 팀원에게 전달하고 추가질문이나 코멘트 남기도록 하겠습니다 비 많이 오는데 조심하세요 멘토님 !

2024-09-22 08:52 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/global/MyCrudRepository.java
> +public interface MyCrudRepository<T, ID> extends Repository<T, ID> {
이 부분 팀원들간에 더 이야기 하고 있어서 내부에서 필요성 검토후 추가 질문드리겠습니다! 감사합니다!

2024-09-22 09:17 UTC, yoo-jaein commented
@jinseohyun1228 설명 감사합니다!

> "템플릿"에 대해서
- 초기 개발 방향을 명확히 잡는 용으로는 괜찮을 것 같네요! 그렇다면 해당 템플릿 클래스들을 상속이나 직접 사용하지 않고 참고만 하는걸까요? 프로젝트가 커지고 복잡해지면 템플릿을 벗어나는 상황이 발생할 것 같고, 상속하는 경우 초반부터 코드 복잡성이 너무 올라갈 것 같아 여쭤봅니다.

> 응답 형식
api 응답 형식은 클라이언트와 서버간에 모여서 협의하는 것이 가장 좋습니다. 서비스와 클라이언트 특성마다 조금씩 다르겠지만, 일반적인 웹 서비스에서 api 응답 형식은 case 1번을 가장 많이 사용합니다.

2024-09-22 23:56 UTC, yoo-jaein approved these changes
원활한 진행을 위해 우선 Approve하겠습니다.
이번 주 신규 작업과 함께 개선 부탁드립니다! 😀

2024-09-22 23:57 UTC, merged

2024-09-23 17:53 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/global/handler/GlobalExceptionHandler.java
> +        System.out.println(e);
말씀 감사합니다! 이 부분 반영하도록 하겠습니다 ~!

2024-09-23 17:55 UTC, jinseohyun1228 commented
>api 응답 형식은 클라이언트와 서버간에 모여서 협의하는 것이 가장 좋습니다. 서비스와 클라이언트 특성마다 조금씩 다르겠지만, 일반적인 웹 서비스에서 api 응답 형식은 case 1번을 가장 많이 사용합니다.

이 부분 프론트 분들과 협의 후 메시지가 필요없으며, 실무에서도 1번을 많이 쓰신다는 멘토님의 말씀을 참고해서 첫번째 케이스를 사용하는 것으로 결정 내렸습니다! 감사합니다.

2024-09-23 17:56 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/global/response/ResultCode.java
> +    GET_ALL_PRODUCTS_SUCCESS(HttpStatus.OK, "P001", "모든 제품 조회 성공"),
팀 내 회의를 통해 성공 코드를 따로 두지 않는 것으로 결정내렸습니다. 감사합니다. (아래에 답변 드렸습니다.)

2024-09-23 17:59 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/global/utils/ResponseHelper.java
> +    public static ResponseEntity<SimpleResultResponseDto> createSimpleResponse(ResultCode resultCode, Map<String, String> headers) {
오! 일급 클래스를 쓰면 컬렉션 함수에 의존하지 않아서 복잡도가 낮아질 것 같습니다. 객체의 불변성을 보장할 수 있다는 것도 좋은 것 같습니다!!

새롭게 알려주셔서 감사합니다 🙇 (멘토링 하는 동안에 많이 배우겠습니다. 잘부탁드립니다.)

이부분 팀원들에게 전달 후 필요하다고 판단되는 부분에 반영하기로 하였습니다.

2024-09-23 17:59 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/template/controller/TemplateController.java
> +    @PostMapping("")
넵 반영하겠습니다.

2024-09-23 18:00 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/template/controller/TemplateController.java
> +    public ResponseEntity<TemplateDomain> getTemplateById(@PathVariable(name = "id") Long id) {
넵! 이후 개발에 반영하겠습니다. 꼼꼼한 피드백 감사합니다 🙇

2024-09-23 18:01 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/template/controller/TemplateController.java
> +        System.out.println(e);
넵 이 에러같은 경우 로그를 남기도록 하겠습니다.

2024-09-23 18:12 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/global/MyCrudRepository.java
> +public interface MyCrudRepository<T, ID> extends Repository<T, ID> {
말씀 감사합니다! 이 부분 반영하도록 하겠습니다 ~!

2024-09-23 18:30 UTC, jinseohyun1228 commented on boomerang/src/main/java/boomerang/global/utils/ResponseHelper.java
> +public class ResponseHelper {
감사합니다. 반영하도록 하겠습니다1

2024-09-24 15:27 UTC, yoo-jaein commented
@jinseohyun1228 답변 감사합니다!

> 실무에서는 어떤 형식으로 개발 스타일을 정하나요?
> 별도의 문서를 사용하는지, 혹은 기존의 코드를 참고하는지 궁금합니다.
> 
> 또한 어느정도로 정하는지도 궁금합니다.
> 메서드명이나, 변수명을 스타일까지 통일하나요??

프로젝트와 서비스의 성격에 따라 적합한 아키텍쳐가 다르고, 어느 상황에 다 쓸수 있는 silver bullet은 없기 때문에 '개발 스타일'을 정하기보단 '코드 컨벤션'을 정합니다.

대부분 [구글 코드 컨벤션](https://google.github.io/styleguide/javaguide.html) 기반으로 에디터 설정을 조금 첨가해서 정합니다. 

팀 단위로 크게 협의하되, 프로젝트 단위로 정하는 약속도 있습니다. (그렇지만 크게 팀 스타일을 벗어나지 X) 

협의한 내용은 별도의 문서(위키)로 남깁니다. 새로운 사람이 들어오면 아마 첫번째로 팀 코드 컨벤션 문서를 볼거에요.
intellij [checkstyle](https://hbase.tistory.com/443)과 같은 플러그인을 사용하는 경우 설정 파일을 팀 내에서 공유하기도 합니다. 
별도 플러그인을 쓰지 않고 그냥 intellij 내의 editor 설정으로만 정하는 경우도 있습니다.

> MyCrudRepository에 대해서

정리하신 글 잘 읽었습니다! 동작을 유추할 수 있다는 의도가 잘 이해되었습니다. ㅎㅎ
기술적으로 문제는 없을 것 같고, 개발할때 약간 귀찮을 순 있겠지만 인터페이스를 좀 더 명시적으로 만들려는 설계상의 선택으로 보이네요.

이미 팀 내에서 협의하신 만큼 그대로 진행해보시면 좋을 것 같습니다.
대신 이름을 My 대신 조금 더 역할에 맞게 수정하면 어떨까요? (CustomCrud~, ExplicitMethod~ 등..)